### ISSUE TITLE
add gradle runner support

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#838]
We should be able to register gradle projects (only system jobs as of now including Build).
in additions it should support:
1) onPush and onPullRequest events
2) sonar static analysis for above events
3) java 11 code to analyze

**Comment by vdelendik** [comment]
feature is delivered: https://github.com/qaprosoft/qps-pipeline/pull/837
test scenario could be confirmed with @SergeyBrenko - he has set of repositories on gradle

**Comment by okamara** [comment]
@SergeyBrenko Could you please add Test scenario steps for this ticket.

**Comment by okamara** [comment]
Can't build a gradle project as jenkins slave uses old java 1.8

**Comment by SergeyBrenko** [comment]
All the points from the issue description can be tested together, but require some **preconditions**:
1. jenkins slave must have java 11 or higher on board
2. sonarqube must have version 7.9 or higher and be properly configured to be able to decorate github pull requests. PR decoration for github is performed using a github app.

**Steps for verification:**
1. [GitHub] prepare a github repo with java based gradle project. this repo should have at least two branches with different steps in order to check the PR-related functionality.
2. [Jenkins] create an organisation and register a repository from point 1. these organisation and repository must be successfully created. by doing this step, the onPush event is partially verified
3. [GitHub] create a github webhooks for the repository in Jenkins from point 2.
4. [Git] push something to the branch of the github repo.
**Expected result:** 
a. [Jenkins] onPush job is triggered and completed successfully.
b. [Sonarqube] a new run for the project is registered (probably with some code smells|bugs|vulnerabilities|etc). the sonar project should have the git branch identifier in the left upper corner.
5. [GitHub]. create a pull request
**Expected result:**
а. [Jenkins] onPullRequest job is triggered and completed successfully.
b. [Sonarqube] a new run for the project is registered (probably with some code smells|bugs|vulnerabilities|etc). you should be able to switch to the PR scan using the branch identifying UI control.
c. [GitHub] the pull request should have a new item with scan results in "Checks" section.

**Comment by okamara** [comment]
Tested. Fixed.
<img width="345" alt="Screen Shot 2020-07-08 at 6 50 18 PM" src="https://user-images.githubusercontent.com/32964663/86940891-fd06a300-c14b-11ea-8600-cc7af27e2bc3.png">
